defaults:
  - base
  - _self_

preprocessor:
  max_num_profiles: -1  # Maximum number of profiles to use per question (-1 to use all)
  max_query_length: 512
  max_document_length: 512

score_model:
  encoder_model: facebook/contriever
  fuse_mode: cross_attn  # Strategy for query-document fusion (concat_hidden, concat_token, cross_attn)
  num_layers: 12         # Number of document Transformer layers
  decoder_hidden_size: 256

reinforce:
  num_samples: 32  # Number of samples, each contains `num_rerank` profiles
  reward: logp     # Type of reward (metric, logp)

wandb_mode: offline
from_pretrained: false

num_epochs: 10
batch_size: 16
gradient_accumulation_steps: 1
max_grad_norm: 1.0
lr: 1e-4

eval_every: 1024
eval_batch_size: 32
