defaults:
  - baseline
  - _self_

run_name: "${run_prefix}/\
  ${reward_type}_${loss_type}_${fuse_mode}/${task}/s${seed}"

retriever: purple

create_prompt_fn:
  retriever: first_k

create_pretokenize_fn:
  encoder_model: ${score_model.encoder_model}
  max_query_length: 512
  max_document_length: 512

score_model:
  encoder_model: facebook/contriever
  fuse_mode: ${fuse_mode}
  num_transformer_layers: 12
  decoder_hidden_size: 256

trainer_args:
  output_dir: outputs/${run_name}
  train_batch_size: 16
  num_train_epochs: 10
  learning_rate: 1e-4
  max_grad_norm: 1.0
  run_name: ${run_name}
  eval_steps: 1024
  eval_batch_size: 32
  resume_from_checkpoint: false
  num_rollouts: 32
  num_retrieve: ${num_retrieve}
  mini_batch_size: 8
  epsilon: 0.2
  reward_type: ${reward_type}
  loss_type: ${loss_type}

reward_type: logprob
loss_type: reinforce
fuse_mode: cross_attn
