defaults:
  - baseline
  - rl: reinforce
  - _self_

run_name: "${hydra:runtime.choices.llm}/\
  ${candidate_retriever}-${num_candidates}/\
  ${retriever}-${num_retrieve}/${hydra:runtime.choices.rl}-${reward}/${task}"

retriever: purple
reward: logp
resume: false

preprocess_fn:
  max_query_length: 512
  max_document_length: 512

score_model:
  encoder_model: facebook/contriever
  fuse_mode: cross_attn
  num_transformer_layers: 12
  decoder_hidden_size: 256

num_epochs: 10
batch_size: 16
max_grad_norm: 1.0
lr: 1e-4

eval_every: 1024
eval_batch_size: 32
